// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_IC3OlKRrMkIKfgKqBRCDCS9EquRnKs',
    appId: '1:753674526152:web:33ca5b3b792db5a48174fd',
    messagingSenderId: '753674526152',
    projectId: 'samudra-firebase',
    authDomain: 'samudra-firebase.firebaseapp.com',
    storageBucket: 'samudra-firebase.firebasestorage.app',
    measurementId: 'G-MHWPZQJHWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5l815TiaGP-WrV1_E0yITNqI8AY_7JU',
    appId: '1:753674526152:android:58db69de8e8900e78174fd',
    messagingSenderId: '753674526152',
    projectId: 'samudra-firebase',
    storageBucket: 'samudra-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0oPiODJIyu1b5zcZs91w7q71HlW9gwE',
    appId: '1:753674526152:ios:75f1e671822fd2658174fd',
    messagingSenderId: '753674526152',
    projectId: 'samudra-firebase',
    storageBucket: 'samudra-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0oPiODJIyu1b5zcZs91w7q71HlW9gwE',
    appId: '1:753674526152:ios:75f1e671822fd2658174fd',
    messagingSenderId: '753674526152',
    projectId: 'samudra-firebase',
    storageBucket: 'samudra-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterClone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC_IC3OlKRrMkIKfgKqBRCDCS9EquRnKs',
    appId: '1:753674526152:web:0a2caffcd92e8bbd8174fd',
    messagingSenderId: '753674526152',
    projectId: 'samudra-firebase',
    authDomain: 'samudra-firebase.firebaseapp.com',
    storageBucket: 'samudra-firebase.firebasestorage.app',
    measurementId: 'G-FGVCXT861W',
  );
}
